<a href="https://colab.research.google.com/github/Sourav-2510/YBI-Internship/blob/main/Product_Review.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Product Review Prediction

###Objective

Women cloth reviews prediction using multi nomial naive bayes.

###Data Source
http://raw.githubusercontent.com/YBI-Foundation/Teaching-Data/main/women%20Clothing%20E-Commerce%20Review.csv

###Import Library

In [1]:
import pandas as pd

In [3]:
import numpy as np

In [4]:
import matplotlib.pyplot as plt 

In [5]:
import seaborn as sns

###Import Dataset

In [7]:
df=pd.read_csv('http://raw.githubusercontent.com/YBI-Foundation/Teaching-Data/main/Women%20Clothing%20E-Commerce%20Review.csv')

###Describe data

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23486 entries, 0 to 23485
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype 
---  ------             --------------  ----- 
 0   Clothing ID        23486 non-null  int64 
 1   Age                23486 non-null  int64 
 2   Title              19676 non-null  object
 3   Review             22641 non-null  object
 4   Rating             23486 non-null  int64 
 5   Recommended        23486 non-null  int64 
 6   Positive Feedback  23486 non-null  int64 
 7   Division           23472 non-null  object
 8   Department         23472 non-null  object
 9   Category           23472 non-null  object
dtypes: int64(5), object(5)
memory usage: 1.8+ MB


In [9]:
df.describe()

Clothing ID           Age        Rating   Recommended  \
count  23486.000000  23486.000000  23486.000000  23486.000000   
mean     918.118709     43.198544      4.196032      0.822362   
std      203.298980     12.279544      1.110031      0.382216   
min        0.000000     18.000000      1.000000      0.000000   
25%      861.000000     34.000000      4.000000      1.000000   
50%      936.000000     41.000000      5.000000      1.000000   
75%     1078.000000     52.000000      5.000000      1.000000   
max     1205.000000     99.000000      5.000000      1.000000   

       Positive Feedback  
count       23486.000000  
mean            2.535936  
std             5.702202  
min             0.000000  
25%             0.000000  
50%             1.000000  
75%             3.000000  
max           122.000000

In [11]:
df.shape

(23486, 10)

###Data Visualization

In [12]:
df.head()

Clothing ID  Age                    Title  \
0          767   33                      NaN   
1         1080   34                      NaN   
2         1077   60  Some major design flaws   
3         1049   50         My favorite buy!   
4          847   47         Flattering shirt   

                                              Review  Rating  Recommended  \
0  Absolutely wonderful - silky and sexy and comf...       4            1   
1  Love this dress!  it's sooo pretty.  i happene...       5            1   
2  I had such high hopes for this dress and reall...       3            0   
3  I love, love, love this jumpsuit. it's fun, fl...       5            1   
4  This shirt is very flattering to all due to th...       5            1   

   Positive Feedback        Division Department   Category  
0                  0       Initmates   Intimate  Intimates  
1                  4         General    Dresses    Dresses  
2                  0         General    Dresses    Dresses  
3                  0  General Petite    Bottoms      Pants  
4                  6         General       Tops    Blouses

In [13]:
df.columns

Index(['Clothing ID', 'Age', 'Title', 'Review', 'Rating', 'Recommended',
       'Positive Feedback', 'Division', 'Department', 'Category'],
      dtype='object')

###Data Preprocessing

In [14]:
df.isna().sum()

Clothing ID             0
Age                     0
Title                3810
Review                845
Rating                  0
Recommended             0
Positive Feedback       0
Division               14
Department             14
Category               14
dtype: int64

6 columns have null value and Title have almost 4000 null values

In [15]:
df[df['Review']==""]=np.NaN

In [16]:
df['Review'].fillna("No Review",inplace=True)

In [17]:
df.isna().sum()

Clothing ID             0
Age                     0
Title                3810
Review                  0
Rating                  0
Recommended             0
Positive Feedback       0
Division               14
Department             14
Category               14
dtype: int64

all the null values from Review column is replaced with 'No Review'

###Define target and feature variable

In [18]:
x=df['Review']

In [19]:
y=df['Rating']

In [20]:
df['Rating'].value_counts()

5.0    13131
4.0     5077
3.0     2871
2.0     1565
1.0      842
Name: Rating, dtype: int64

###Train Test Split

In [21]:
from sklearn.model_selection import train_test_split

In [22]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=2529)

In [23]:
x_train.shape

(16440,)

In [24]:
x_test.shape

(7046,)

###modeling

Get Feature Text Conversion to Tokens

In [26]:
from sklearn.feature_extraction.text import CountVectorizer

In [29]:
cv=CountVectorizer(lowercase=True,analyzer='word',ngram_range=(2,3),stop_words='english',max_features=5000)

In [30]:
x_train=cv.fit_transform(x_train)

In [31]:
cv.get_feature_names_out()

array(['00 petite', '0p fit', '10 12', ..., 'years old', 'yellow color',
       'yoga pants'], dtype=object)

In [32]:
x_train.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [33]:
x_test=cv.fit_transform(x_test)

In [34]:
x_test.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

###Model Train

In [36]:
from sklearn.naive_bayes import MultinomialNB

In [37]:
model=MultinomialNB()

In [38]:
model.fit(x_train,y_train)

MultinomialNB()

###Model Evaluation

In [39]:
y_pred=model.predict(x_test)

In [40]:
y_pred.shape

(7046,)

In [41]:
y_pred

array([2., 3., 3., ..., 5., 4., 5.])

In [42]:
model.predict_proba(x_test)

array([[0.26692373, 0.35957477, 0.30830537, 0.04730174, 0.01789439],
       [0.09725869, 0.09370016, 0.48762968, 0.26285916, 0.05855232],
       [0.21322638, 0.0344866 , 0.6775651 , 0.01713515, 0.05758676],
       ...,
       [0.22922895, 0.0288237 , 0.07354507, 0.02725008, 0.6411522 ],
       [0.01591788, 0.00115913, 0.00471111, 0.76076036, 0.21745151],
       [0.06184667, 0.09982129, 0.01834076, 0.04535696, 0.77463432]])

In [43]:
from sklearn.metrics import confusion_matrix,classification_report

In [44]:
print(confusion_matrix(y_test,y_pred))

[[  29   26   35   32  141]
 [  48   43   91   75  186]
 [  78   96  152  172  326]
 [ 125  129  212  301  742]
 [ 327  330  394  648 2308]]


In [45]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

         1.0       0.05      0.11      0.07       263
         2.0       0.07      0.10      0.08       443
         3.0       0.17      0.18      0.18       824
         4.0       0.25      0.20      0.22      1509
         5.0       0.62      0.58      0.60      4007

    accuracy                           0.40      7046
   macro avg       0.23      0.23      0.23      7046
weighted avg       0.43      0.40      0.42      7046



###Recategories Rating as poor and good

In [46]:
df.replace({'Rating':{1:0,2:0,3:0,4:1,5:1}},inplace=True)

In [47]:
df['Rating']

0        1.0
1        1.0
2        0.0
3        1.0
4        1.0
        ... 
23481    1.0
23482    0.0
23483    0.0
23484    0.0
23485    1.0
Name: Rating, Length: 23486, dtype: float64

In [48]:
x=df['Review']

In [49]:
y=df['Rating']

###Train Test Split

In [50]:
from sklearn.model_selection import train_test_split

In [51]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=2529)

In [52]:
from sklearn.feature_extraction.text import CountVectorizer

In [53]:
cv=CountVectorizer(lowercase=True,analyzer='word',ngram_range=(2,3),stop_words='english',max_features=5000)

In [54]:
x_train=cv.fit_transform(x_train)

In [55]:
x_test=cv.fit_transform(x_test)

###ReModeling

In [56]:
from sklearn.naive_bayes import MultinomialNB

In [57]:
model=MultinomialNB()

In [58]:
model.fit(x_train,y_train)

MultinomialNB()

###Model Prediction

In [59]:
y_pred=model.predict(x_test)

In [60]:
y_pred

array([0., 0., 0., ..., 1., 1., 1.])

In [61]:
from sklearn.metrics import confusion_matrix,classification_report

In [62]:
print(confusion_matrix(y_test,y_pred))

[[ 482 1048]
 [ 973 4543]]


In [63]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

         0.0       0.33      0.32      0.32      1530
         1.0       0.81      0.82      0.82      5516

    accuracy                           0.71      7046
   macro avg       0.57      0.57      0.57      7046
weighted avg       0.71      0.71      0.71      7046



The developed model have an accuracy of 70%